version: '3.8'
services:
    nginx-ssl:
      container_name: nginx-ssl
      image: nginx:latest
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./certs/:/etc/nginx/certs/
      ports:
          - "80:80"
          - "443:443"